apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-prediction-deployment
  labels:
    app: insurance-prediction
spec:
  template:
    spec:
      containers:
        - name: insurance-prediction
          image: {{IMAGE_REF}}
          ports:
            - containerPort: 80