apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-read-run-${random_id.ci_pipeline_run_id.hex}
  namespace: cicd
spec:
  pipelineRef:
    name: clone-read
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: ${kubernetes_secret.git_credentials.metadata.0.name}
  params:
    - name: repo-url
      value: http://gitea-http.infrastructure:3000/ok-user/ok-gitea-repository.git