apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ci-pipelinebinding
  namespace: cicd
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: cicd
    - name: gitrepositoryurl
      value: "http://gitea-http.infrastructure:3000/$(body.repository.full_name)"
    - name: envgitrepositoryurl
      value: "http://gitea-http.infrastructure:3000/ok-user/environment-repository.git"
    - name: imagereference
      value: "registry-service.infrastructure:5000/insurance-prediction:$(body.head_commit.id)"
    - name: path-to-patch-file
      value: "patches/version-patch.yaml"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ci-listener
  namespace: cicd
spec:
  serviceAccountName: m3-sa
  triggers:
    - bindings:
        - ref: ci-pipelinebinding
      template:
        ref: ci-triggertemplate
