ingress:
  enabled: true
  hosts:
    - host: gitea.local
      paths:
        - path: /
          pathType: Prefix

gitea:
  admin:
    username: ok-admin
    password: ok-admin

service:
  http:
    type: NodePort
    nodePort: 30030