ingress:
  enabled: true
  hosts:
    - host: gitea.local
      paths:
        - path: /
          pathType: Prefix

gitea:
  admin:
    username: mlops-admin
    password: mlops-admin
  config:
    webhomlops:
      ALLOWED_HOST_LIST: "*,10.96.207.247,el-ci-listener.cicd.svc.cluster.local"

service:
  http:
    type: NodePort
    nodePort: 30030