apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: insurance-prediction-deployment
    path: ./patches/version-patch.yaml

resources:
  - ../base/
