apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently
  namespace: observability
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evidently
  template:
    metadata:
      labels:
        app: evidently
    spec:
      containers:
        - name: evidently
          image: openknowledge/evidently
          ports:
            - containerPort: 8085
